%% save_allfigsJASA.m
% 
% Save multiple open figures as FIG and EPS images
%
% Run this script after figures have been opened, to keep ordering by
% figure number
%
% Dependencies: none
% Last edit: 6/12/2019
%
% Author: George Liu

disp('Select folder for saving figures... ')
FolderName = uigetdir;   % Your destination folder
disp(FolderName)

FigList = findobj(allchild(0), 'flat', 'Type', 'figure');

%% Noise variance plots
DATASET_DATE_IDENTIFIER = '6-8-19_dataset5';

FIGNAMES = {...
    '1_averageABR_abs_', ...
    '2_averageABR_rel_', ...
    '3_singletraces_abs_', ...
    '4_singletraces_rel_', ...
    '5_peaks_troughs_', ...
    '6_threshold_maxp2p_vs_dB_3se_', ...
    '7_lags_vs_dB_xcovmax50_linearfit_', ...
    '8_xcov_traces_aveABR_', ...
    '9_maxxcov_vs_dB_cut50_', ...
    '10_hist_maxp2p_innerprod_', ...
    '11_psychometric_vpp-sp_T10_fpr05_', ...
    '12_psychometric_innerprod_xcovmax50_fpr05_', ...
    '13_pval_ranksum_vpp-sp_T10_', ....
    '14_pval_ks_vpp-sp_T10_', ...
    '15_pval_ranksum_innerprod_xcovmax50_', ...
    '16_pval_ks_innerprod_xcovmax50_', ...
    '17_vpp_vs_dB_aveABR_', ...
    '18_innerprod_vs_dB_aveABR_', ...
    '19_threshold_innerprod_vs_dB_3se_', ...
    '20_psychometric_vpp-sp_T10_3se_', ...
    '21_psychometric_innerprod_xcovmax50_3se_', ...
    '22_roc_vpp-sp_', ...
    '23_roc_innerprod_', ...
    '24_fpr_vs_treshold_Vpp-mp_T10_', ...
    '25_fpr_vs_cutoff_Vpp-mp_T10_', ...
    '26_cutoff_vs_treshold_Vpp-mp_T10_', ...
    '27_fpr_vs_treshold_innerprod_', ...
    '28_fpr_vs_cutoff_innerprod_', ...
    '29_cutoff_vs_treshold_innerprod_', ...
    };
    

% for iFig = 1:length(FigList)
for i = 1:length(FigList)
    iFig = length(FigList) - i + 1;
    disp(['Saving figure ', num2str(i), ' out of ', num2str(length(FigList))])
    FigHandle = FigList(iFig);
    FigName   = FIGNAMES{i};  % Adjust the FigName to your needs.
    saveas(FigHandle, fullfile(FolderName, [FigName, DATASET_DATE_IDENTIFIER, '.fig']));    % FIG file
    saveas(FigHandle, fullfile(FolderName, [FigName, DATASET_DATE_IDENTIFIER, '.eps']));    % EPS file
end

disp('Done.')