%% save_allfigsJASA.m
% 
% Save multiple open figures as FIG and EPS images
%
% Run this script after figures have been opened, to keep ordering by
% figure number
%
% Dependencies: none
% Last edit: 6/12/2019
%
% Author: George Liu

disp('Select folder for saving figures... ')
FolderName = uigetdir;   % Your destination folder
disp(FolderName)

FigList = findobj(allchild(0), 'flat', 'Type', 'figure');


%% Noise variance plots
DATASET_DATE_IDENTIFIER = '_3-8-19_dataset2';

FIGNAMES = {...
    '1_averageABR_abs', ...
    '2_averageABR_rel', ...
    '3_singletraces_abs', ...
    '4_singletraces_rel', ...
    '5_peaks_troughs', ...
    '6_threshold_maxp2p_vs_dB_3se', ...
    '7_lags_vs_dB_xcovmax50_linearfit', ...
    '8_xcov_traces_aveABR', ...
    '9_maxxcov_vs_dB_cut50', ...
    '10_hist_maxp2p_innerprod', ...
    '11_psychometric_vpp-sp_T10_fpr05', ...
    '12_psychometric_innerprod_xcovmax50_fpr05', ...
    '13_pval_ranksum_vpp-sp_T10', ....
    '14_pval_ks_vpp-sp_T10', ...
    '15_pval_ranksum_innerprod_xcovmax50', ...
    '16_pval_ks_innerprod_xcovmax50', ...
    '17_vpp_vs_dB_aveABR', ...
    '18_innerprod_vs_dB_aveABR', ...
    '19_threshold_innerprod_vs_dB_3se', ...
    '20_psychometric_vpp-sp_T10_3se', ...
    '21_psychometric_innerprod_xcovmax50_3se', ...
    '22_roc_vpp-sp', ...
    '23_roc_innerprod', ...
    '24_fpr_vs_treshold_Vpp-mp_T10', ...
    '25_fpr_vs_cutoff_Vpp-mp_T10', ...
    '26_cutoff_vs_treshold_Vpp-mp_T10', ...
    '27_fpr_vs_treshold_innerprod', ...
    '28_fpr_vs_cutoff_innerprod', ...
    '29_cutoff_vs_treshold_innerprod', ...
    };
    

% for iFig = 1:length(FigList)
for i = 1:length(FigList)
    iFig = length(FigList) - i + 1;
    disp(['Saving figure ', num2str(i), ' out of ', num2str(length(FigList))])
    FigHandle = FigList(iFig);
    FigName   = FIGNAMES{i};  % Adjust the FigName to your needs.
    saveas(FigHandle, fullfile(FolderName, [FigName, DATASET_DATE_IDENTIFIER, '.fig']));    % FIG file
%     saveas(FigHandle, fullfile(FolderName, [FigName, DATASET_DATE_IDENTIFIER, '.eps']));    % EPS file
    set(FigHandle, 'Position', get(0, 'Screensize')); % make figure full screen except title bar
    print(FigHandle, fullfile(FolderName, [FigName, DATASET_DATE_IDENTIFIER, '.eps']), '-depsc', '-loose'); % save EPS file with color
end

disp('Done.')